MacOS tests updates
vasily-v-ryabov/pywinauto pull request #11
Opened 2019-12-01 10:45 UTC by zemtsov-artem

2020-02-15 18:05 UTC, zemtsov-artem commented
Is there any blocker to merge it ?

2020-02-16 13:37 UTC, zemtsov-artem commented on .travis.yml
> +  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then sudo sqlite3 "/Library/Application Support/com.apple.TCC/TCC.db" "INSERT INTO access VALUES ('kTCCServiceAccessibility','com.apple.dt.Xcode-Helper',0,1,1,N
Remove changes

2020-03-05 16:34 UTC, vasily-v-ryabov requested changes

2020-03-05 16:34 UTC, vasily-v-ryabov commented on pywinauto/macos/macos_functions.py
>          print ("App is not allready running.Can't get instance")
`allready` -> `already`

2020-03-05 16:34 UTC, vasily-v-ryabov commented on pywinauto/macos/macos_functions.py
> +            raise RuntimeError('Error launching specified application. Result: {}'.format(r))
Too long indent

2020-03-05 16:34 UTC, vasily-v-ryabov commented on pywinauto/macos/macos_functions.py
> +            {},
Word wrap seems not necessary, it should fit into 120 symbols.

2020-03-05 16:34 UTC, vasily-v-ryabov commented on pywinauto/macos/macos_functions.py
>  from ApplicationServices import *
It would be nice to eliminate wildcard import.

2020-03-05 16:34 UTC, vasily-v-ryabov commented on pywinauto/macos/macos_functions.py
>  import os
Built-in modules should be imported first: os, subprocess. Then 3-rd party modules (six, all PyObjC stuff), then project specific modules. Grouped imports should be separated by empty line.

2020-04-19 20:19 UTC, zemtsov-artem commented
All tests are passed.
Fixed code style as well.

2020-04-20 09:28 UTC, vasily-v-ryabov approved these changes

2020-04-20 09:32 UTC, merged