macOS setup
vasily-v-ryabov/pywinauto pull request #12
Opened 2020-02-11 21:17 UTC by zemtsov-artem

2020-02-11 21:19 UTC, zemtsov-artem commented
@vasily-v-ryabov could you please confirm that there are enough changes for setup.
I saw that we use dev-requirements.txt in AppVeyor.yml and landscape.yml. 
Shall I update them?

2020-02-13 17:19 UTC, vasily-v-ryabov commented on setup.py
> +        'codecov',
`codecov` is a requirement for running tests with coverage (for development only). `setup.py` must contain only production needed packages.

2020-02-13 17:22 UTC, vasily-v-ryabov commented
`dev-requirements.txt` contains all packages needed for development of pywinauto. This is not for end users. `setup.py` is for end user installation. There is new feature in `pip` to add `sys.platform` dependent packages into requirements file. Ideally we can modify `dev-requirements.txt` this way.

2020-02-15 18:33 UTC, zemtsov-artem commented
> `dev-requirements.txt` contains all packages needed for development of pywinauto. This is not for end users. `setup.py` is for end user installation. There is new feature in `pip` to add `sys.platform` dependent packages into requirements file. Ideally we can modify `dev-requirements.txt` this way.

Applied

2020-02-16 13:33 UTC, vasily-v-ryabov requested changes

2020-02-16 13:33 UTC, vasily-v-ryabov commented on dev-requirements.txt
> +pywin32                                   ;sys_platform == 'pywin32'
Maybe `sys_platform == 'win32'` ?

2020-02-16 13:33 UTC, vasily-v-ryabov commented on dev-requirements.txt
> +#
`python-xlib` should be mentioned

2020-03-05 16:15 UTC, vasily-v-ryabov requested changes

2020-03-05 16:15 UTC, vasily-v-ryabov commented on dev-requirements.txt
> +# Darwin specific packages
`Darwin` -> `macOS`, `Win32` -> `Windows`

2020-04-19 18:52 UTC, vasily-v-ryabov approved these changes

2020-04-20 08:30 UTC, merged